### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by Lewiscowles1986** [CODESIGN2/mailhog-docker#12]
Just documenting how I got this deployed at a job I'm at

```
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mailhog
  template:
    metadata:
      labels:
        service: mailhog
    spec:
      containers:
      - name: app
        image: cd2team/mailhog
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: dev
spec:
  type: NodePort
  selector:
    service: mailhog
  ports:
  - port: 25
    targetPort: 1025
    protocol: TCP
    name: smtp
  - port: 3000
    targetPort: 8025
    protocol: TCP
    name: web
```
